# Сообщение, которое будет отправлено игроку, если рядом никого нет, чтобы его услышать.
no-one-heard-message: '&c[!] Вас никто не услышал... Рядом никого нет.'

# Формат стрелки направления, появляющейся в action bar при получении сообщения в локальном чате.
# Переменные: %dist% = расстояние в блоках, %arrow% = стрелка направления, %player% = имя отправителя
direction-format: '&8[&b%dist%m %arrow%&8]'

auraskills-broadcast:
  enabled: true
  message: '&8[&bНавыки&8] &7Игрок &b%player% &7повысил навык &b%skill% &7до уровня &b%level%&7! Общая сила: &b%power%'

thematic-messages: []

